version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=db
      - DJANGO_DB_USER=user
      - DJANGO_DB_PASSWORD=admin

  db:
    build:
      context: .
      dockerfile: db.Dockerfile

  init:
    build:
      context: .
      dockerfile: init.Dockerfile
    depends_on:
      - db
